
import { Product } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Products', icon: 'fa-box-open' },
  { id: 'homedecor', name: 'Home Decor', icon: 'fa-house-chimney-window' },
  { id: 'clothing', name: 'Clothing', icon: 'fa-shirt' },
  { id: 'jewelry', name: 'Jewelry', icon: 'fa-gem' },
  { id: 'pottery', name: 'Pottery', icon: 'fa-mountain' },
  { id: 'textiles', name: 'Textiles', icon: 'fa-rug' },
  { id: 'gifts', name: 'Gifts', icon: 'fa-gift' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Hand-painted Ceramic Vase',
    description: 'A beautiful blue and white ceramic vase, hand-painted by traditional artisans in Rajasthan.',
    price: 1250,
    category: 'pottery',
    sellerId: 's1',
    sellerName: 'Amit Artisans',
    images: ['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800'],
    tags: ['blue', 'ceramic', 'handmade', 'vase'],
    rating: 4.8,
    reviews: 124,
    weightInGrams: 1200,
    story: 'This vase represents the blue pottery traditions passed down through generations in my family.'
  },
  {
    id: 'v1',
    name: 'Emerald Crackle Glaze Vase',
    description: 'A tall, elegant ceramic vase featuring a unique emerald green crackle glaze finish. Each piece has a distinct pattern created during the firing process.',
    price: 3400,
    category: 'pottery',
    sellerId: 's1',
    sellerName: 'Amit Artisans',
    images: ['https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?auto=format&fit=crop&q=80&w=800'],
    tags: ['emerald', 'green', 'crackle', 'vase', 'pottery'],
    rating: 4.9,
    reviews: 56,
    weightInGrams: 1500,
    story: 'Inspired by the deep forests of the Western Ghats, this glaze took six months to perfect.'
  },
  {
    id: 'v2',
    name: 'Rustic Terracotta Flower Pot',
    description: 'Traditional unglazed terracotta vase with hand-etched tribal patterns. Perfect for dried flowers or as a standalone decor piece.',
    price: 850,
    category: 'pottery',
    sellerId: 's9',
    sellerName: 'Earthen Souls',
    images: ['https://images.unsplash.com/photo-1590736910119-91500779836a?auto=format&fit=crop&q=80&w=800'],
    tags: ['terracotta', 'rustic', 'etched', 'vase'],
    rating: 4.5,
    reviews: 38,
    weightInGrams: 2200
  },
  {
    id: 'v3',
    name: 'Speckled White Stoneware Vase',
    description: 'Minimalist stoneware vase with a soft speckled finish. Modern silhouette meets ancient crafting techniques.',
    price: 2100,
    category: 'pottery',
    sellerId: 's10',
    sellerName: 'Modern Mud',
    images: ['https://images.unsplash.com/photo-1490312278390-ab6414f81c81?auto=format&fit=crop&q=80&w=800'],
    tags: ['minimalist', 'stoneware', 'white', 'vase'],
    rating: 4.7,
    reviews: 92,
    weightInGrams: 950
  },
  {
    id: '2',
    name: 'Block-Printed Cotton Kurta',
    description: 'Hand-block printed indigo kurta made from 100% organic cotton. Traditional Jaipur technique.',
    price: 1850,
    category: 'clothing',
    sellerId: 's2',
    sellerName: 'Jaipur Threads',
    images: ['https://images.unsplash.com/photo-1596462502278-27bf8637368c?auto=format&fit=crop&q=80&w=800'],
    tags: ['cotton', 'kurta', 'indigo'],
    rating: 4.9,
    reviews: 42,
    weightInGrams: 300
  },
  {
    id: '3',
    name: 'Silver Filigree Earrings',
    description: 'Delicate handcrafted silver earrings featuring traditional filigree patterns.',
    price: 2200,
    category: 'jewelry',
    sellerId: 's3',
    sellerName: 'Silver Craft',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800'],
    tags: ['silver', 'jewelry', 'earrings'],
    rating: 4.7,
    reviews: 89,
    weightInGrams: 50
  },
  {
    id: '4',
    name: 'Hand-Carved Wooden Partition',
    description: 'Exquisite Sheesham wood room divider with intricate floral carvings. A masterpiece of woodcraft.',
    price: 12000,
    category: 'homedecor',
    sellerId: 's4',
    sellerName: 'Saharanpur Arts',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e35ca?auto=format&fit=crop&q=80&w=800'],
    tags: ['wood', 'furniture', 'carved'],
    rating: 5.0,
    reviews: 12,
    weightInGrams: 8500
  },
  {
    id: '5',
    name: 'Hand-Woven Pashmina Shawl',
    description: 'Authentic 100% Pashmina wool shawl from Kashmir. Soft, warm, and timelessly elegant.',
    price: 15500,
    category: 'textiles',
    sellerId: 's5',
    sellerName: 'Kashmir Looms',
    images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&q=80&w=800'],
    tags: ['wool', 'pashmina', 'luxury'],
    rating: 4.9,
    reviews: 28,
    weightInGrams: 250
  },
  {
    id: '6',
    name: 'Artisan Gourmet Gift Box',
    description: 'A curated collection of handmade organic chocolates, tea, and a hand-poured soy candle.',
    price: 2500,
    category: 'gifts',
    sellerId: 's6',
    sellerName: 'Soulful Hampers',
    images: ['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=800'],
    tags: ['gift', 'hamper', 'organic'],
    rating: 4.8,
    reviews: 210,
    weightInGrams: 1500
  },
  {
    id: '8',
    name: 'Kantha Work Cotton Throw',
    description: 'Hand-stitched vintage Kantha throw from Bengal. Double-sided with unique patterns.',
    price: 4500,
    category: 'textiles',
    sellerId: 's8',
    sellerName: 'Bengal Heritage',
    images: ['https://images.unsplash.com/photo-1595053545196-85750033c415?auto=format&fit=crop&q=80&w=800'],
    tags: ['kantha', 'throw', 'vintage'],
    rating: 4.7,
    reviews: 33,
    weightInGrams: 900
  }
];
